kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: te-nfs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: "${file-system-id}"
  directoryPerms: "700"
reclaimPolicy: Retain
